version: '3.5'

services:
  app:
    build: .
    container_name: warstation_app
    ports:
      - "443:443"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./certs:/etc/ssl/certs
    networks:
      - proxy_nets

  server:
    image: easypi/stunnel
    ports:
      - "9080:9080"
    volumes:
      - ./stunnel_epi/data:/etc/stunnel
      - ./stunnel_epi/data/server.conf:/etc/stunnel/stunnel.conf
    restart: always
    networks:
      - proxy_nets

  client:
    image: easypi/stunnel
    ports:
      - "9050:9050"
      - "9051:9051"
    volumes:
      - ./stunnel_epi/data:/etc/stunnel
      - ./stunnel_epi/data/client.conf:/etc/stunnel/stunnel.conf
    extra_hosts:
      - server:1.2.3.4
    restart: always
    networks:
      - proxy_nets

networks:
  proxy_nets:
    driver: bridge