spring.application.name=api
#server.ssl.key-store=classpath:certs/server.pfx
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=myproxy

server.ssl.key-store=classpath:certs/server.pfx
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=te-d7f97a4c-d271-4196-91a5-92e5cd3bd40d
server.ssl.enabled=false

server.port=8080
#spring.main.web-application-type=reactive
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.reactor.netty.http.client=DEBUG
#server.address=0.0.0.0

#server.ssl.client-auth=none
#server.forward-headers-strategy=native
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*


# Allow insecure backend connections
#spring.cloud.gateway.httpclient.ssl.use-insecure-trust-manager=true

#spring.cloud.gateway.httpclient.ssl.handshake-timeout=10000ms
#spring.cloud.gateway.httpclient.ssl.close-notify-flush-timeout=3000ms
#spring.cloud.gateway.httpclient.ssl.close-notify-read-timeout=3000ms
#
#spring.cloud.gateway.routes[0].id=my-secure-service
#spring.cloud.gateway.routes[0].uri=https://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/warstation/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
#
#
## Add SSL truststore if needed
#spring.cloud.gateway.httpclient.ssl.key-store=classpath:certs/server.pfx
#spring.cloud.gateway.httpclient.ssl.key-store-password=changeit
#spring.cloud.gateway.httpclient.ssl.key-store-type=PKCS12
#spring.cloud.gateway.httpclient.ssl.key-alias=te-d7f97a4c-d271-4196-91a5-92e5cd3bd40d

