client = no
chroot = /var/run/stunnel
setuid = nobody
setgid = nogroup
pid = /stunnel.pid
debug = 7

[https_proxy]
accept = 443
connect = warstation_app:443

cert = /etc/stunnel/certs/server.crt
key = /etc/stunnel/certs/server.key
verify = 0